name: Build and upload Docker (Buildx)

on:
  push:
    branches:
      - main

jobs:
  devops:
    name: Docker image build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        images:
          - wbia-base wbia-provision wbia

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: 3.8

      # Log into image registries
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: wildmebot
          password: ${{ secrets.WBIA_WILDMEBOT_DOCKER_HUB_TOKEN }}

      - name: Create Buildx context
        run: |
          docker buildx create --name multi-arch-builder --use

      # Build images
      - name: Build images
        run: |
          # Build Image
          cd devops/
          bash build.sh ${{ matrix.images }}
